# docker-compose.yaml
version: '3.8'

services:
  # Изменено имя сервиса с "web" на "app"
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      # Монтируем код для удобства разработки
      - .:/app
      # Добавляем анонимный том для .venv, чтобы избежать конфликтов с локальным venv
      - /app/.venv
      # Если вам нужен доступ к файлу config/db_conf_pg.txt внутри контейнера по другим причинам,
      # можете также смонтировать папку config, но для получения DATABASE_URL это уже не нужно
      - ./config:/app/config # Опционально, если другие части приложения читают конфиг файлы
    environment:
      # Переменная DATABASE_URL будет взята из файла .env
      - DATABASE_URL=${DATABASE_URL}
      - FLASK_ENV=production # Или development
      # Если в db_conf_pg.txt у вас есть другие параметры, их тоже можно добавить в .env
      # и использовать здесь, например:
      # - OTHER_DB_PARAM=${OTHER_DB_PARAM_FROM_ENV}
    depends_on:
      - db

  # Сервис для базы данных PostgreSQL остается прежним
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      # Используйте те же учетные данные, что и в DATABASE_URL в .env
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Ex-machina6891
      - POSTGRES_DB=gig_vospit
    volumes:
      - db_data:/var/lib/postgresql/data
    # restart: always


# Определение именованных томов
volumes:
  db_data:
