"""fix_vizit_and_relationships

Revision ID: 81cc2b4df327
Revises: 
Create Date: 2025-04-22 16:39:52.558060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81cc2b4df327'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applicant', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('applicant_type_id')
        batch_op.drop_column('attestation_type_id')
        batch_op.drop_column('work_field_id')
        batch_op.drop_column('last_name')
        batch_op.drop_column('contingent_id')

    with op.batch_alter_table('applicant_contract', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vizit_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'vizit', ['vizit_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applicant_contract', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('vizit_id')

    with op.batch_alter_table('applicant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contingent_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=80), nullable=False))
        batch_op.add_column(sa.Column('work_field_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('attestation_type_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('applicant_type_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'work_field', ['work_field_id'], ['id'])
        batch_op.create_foreign_key(None, 'contingent', ['contingent_id'], ['id'])
        batch_op.create_foreign_key(None, 'attestation_type', ['attestation_type_id'], ['id'])
        batch_op.create_foreign_key(None, 'applicant_type', ['applicant_type_id'], ['id'])

    # ### end Alembic commands ###
